//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t set the pin more than 250 feet from your current location.
        /// </summary>
        public static string msgCanNotSetPin {
            get {
                return ResourceManager.GetString("msgCanNotSetPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string msgEmptyPassword {
            get {
                return ResourceManager.GetString("msgEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value cannot be empty.
        /// </summary>
        public static string msgEmptyStringError {
            get {
                return ResourceManager.GetString("msgEmptyStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email below and we&apos;ll reset your password..
        /// </summary>
        public static string msgEnterEmail {
            get {
                return ResourceManager.GetString("msgEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be a valid email address..
        /// </summary>
        public static string msgInvalidEmailError {
            get {
                return ResourceManager.GetString("msgInvalidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string msgInvalidPassword {
            get {
                return ResourceManager.GetString("msgInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string msgInvalidUsername {
            get {
                return ResourceManager.GetString("msgInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicensePlate\Vin is required.
        /// </summary>
        public static string msgLicensePlateRequired {
            get {
                return ResourceManager.GetString("msgLicensePlateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( No camera available.
        /// </summary>
        public static string msgNoCameraAvailable {
            get {
                return ResourceManager.GetString("msgNoCameraAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection. Please check your connection and try again..
        /// </summary>
        public static string msgNoInternetConnection {
            get {
                return ResourceManager.GetString("msgNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should match.
        /// </summary>
        public static string msgPasswordsShouldMatch {
            get {
                return ResourceManager.GetString("msgPasswordsShouldMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be a valid email address.
        /// </summary>
        public static string msgShouldBeEmailAddress {
            get {
                return ResourceManager.GetString("msgShouldBeEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        public static string msgStateRequired {
            get {
                return ResourceManager.GetString("msgStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on location.
        /// </summary>
        public static string msgTurnOnLocation {
            get {
                return ResourceManager.GetString("msgTurnOnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be sure to capture the license plate, video should not exceed 60 sec.
        /// </summary>
        public static string msgVideoRequired {
            get {
                return ResourceManager.GetString("msgVideoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation has been submitted.
        /// </summary>
        public static string msgViolationsubmitted {
            get {
                return ResourceManager.GetString("msgViolationsubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Video.
        /// </summary>
        public static string txtAddVideo {
            get {
                return ResourceManager.GetString("txtAddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? SIGN IN!.
        /// </summary>
        public static string txtAlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("txtAlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City App.
        /// </summary>
        public static string txtAppName {
            get {
                return ResourceManager.GetString("txtAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string txtCancel {
            get {
                return ResourceManager.GetString("txtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation Number.
        /// </summary>
        public static string txtCitationNumber {
            get {
                return ResourceManager.GetString("txtCitationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string txtColor {
            get {
                return ResourceManager.GetString("txtColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Location.
        /// </summary>
        public static string txtConfirmLocation {
            get {
                return ResourceManager.GetString("txtConfirmLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string txtConfirmPassword {
            get {
                return ResourceManager.GetString("txtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Printers.
        /// </summary>
        public static string txtDiscoveredPrinters {
            get {
                return ResourceManager.GetString("txtDiscoveredPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering printers....
        /// </summary>
        public static string txtDiscoveringPrinters {
            get {
                return ResourceManager.GetString("txtDiscoveringPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? SIGN UP!.
        /// </summary>
        public static string txtDontHaveAnAccount {
            get {
                return ResourceManager.GetString("txtDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string txtEdit {
            get {
                return ResourceManager.GetString("txtEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adress.
        /// </summary>
        public static string txtEmailAdress {
            get {
                return ResourceManager.GetString("txtEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string txtForgotPassword {
            get {
                return ResourceManager.GetString("txtForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string txtForgoYourtPassword {
            get {
                return ResourceManager.GetString("txtForgoYourtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string txtHome {
            get {
                return ResourceManager.GetString("txtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the remote server. Please try again latter..
        /// </summary>
        public static string txtHttpRequestError {
            get {
                return ResourceManager.GetString("txtHttpRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string txtImage {
            get {
                return ResourceManager.GetString("txtImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string txtLatitude {
            get {
                return ResourceManager.GetString("txtLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        public static string txtLicensePlate {
            get {
                return ResourceManager.GetString("txtLicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate or Vin.
        /// </summary>
        public static string txtLicensePlateOrVin {
            get {
                return ResourceManager.GetString("txtLicensePlateOrVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string txtLocation {
            get {
                return ResourceManager.GetString("txtLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Description.
        /// </summary>
        public static string txtLocationDescription {
            get {
                return ResourceManager.GetString("txtLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string txtLogin {
            get {
                return ResourceManager.GetString("txtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string txtLogOut {
            get {
                return ResourceManager.GetString("txtLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string txtLongitude {
            get {
                return ResourceManager.GetString("txtLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string txtMake {
            get {
                return ResourceManager.GetString("txtMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string txtMessage {
            get {
                return ResourceManager.GetString("txtMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string txtModel {
            get {
                return ResourceManager.GetString("txtModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string txtMore {
            get {
                return ResourceManager.GetString("txtMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string txtNext {
            get {
                return ResourceManager.GetString("txtNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accounts.
        /// </summary>
        public static string txtNoAccounts {
            get {
                return ResourceManager.GetString("txtNoAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submisions yet.
        /// </summary>
        public static string txtNoSubmisionYet {
            get {
                return ResourceManager.GetString("txtNoSubmisionYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string txtOK {
            get {
                return ResourceManager.GetString("txtOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers not found.
        /// </summary>
        public static string txtPrintersNotFound {
            get {
                return ResourceManager.GetString("txtPrintersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Parking Violation.
        /// </summary>
        public static string txtPrintParkingViolation {
            get {
                return ResourceManager.GetString("txtPrintParkingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string txtRegister {
            get {
                return ResourceManager.GetString("txtRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string txtRememberMe {
            get {
                return ResourceManager.GetString("txtRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string txtResetPassword {
            get {
                return ResourceManager.GetString("txtResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string txtSelect {
            get {
                return ResourceManager.GetString("txtSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Printer.
        /// </summary>
        public static string txtSelectPrinter {
            get {
                return ResourceManager.GetString("txtSelectPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence plate state:.
        /// </summary>
        public static string txtSelectState {
            get {
                return ResourceManager.GetString("txtSelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string txtSend {
            get {
                return ResourceManager.GetString("txtSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string txtSkip {
            get {
                return ResourceManager.GetString("txtSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string txtStatus {
            get {
                return ResourceManager.GetString("txtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submision History.
        /// </summary>
        public static string txtSubmisionHistory {
            get {
                return ResourceManager.GetString("txtSubmisionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string txtType {
            get {
                return ResourceManager.GetString("txtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string txtUsername {
            get {
                return ResourceManager.GetString("txtUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Infromation.
        /// </summary>
        public static string txtVehicleInfromation {
            get {
                return ResourceManager.GetString("txtVehicleInfromation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string txtVideo {
            get {
                return ResourceManager.GetString("txtVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string txtViewAll {
            get {
                return ResourceManager.GetString("txtViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Form.
        /// </summary>
        public static string txtViolationForm {
            get {
                return ResourceManager.GetString("txtViolationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Title.
        /// </summary>
        public static string txtViolationTitle {
            get {
                return ResourceManager.GetString("txtViolationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Video.
        /// </summary>
        public static string txtWatchVideo {
            get {
                return ResourceManager.GetString("txtWatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string txtYear {
            get {
                return ResourceManager.GetString("txtYear", resourceCulture);
            }
        }
    }
}
